### PR TITLE
Add support for snap_penalty parameter

### PR DESCRIPTION
**Pull request by pawel-wroniszewski**

### CODE REVIEW

**Comment by danielnaumau** [comment]
Don't forget to bump the version and fix the linter, the rest looks good

**Review by danielnaumau — APPROVED** [review]

**Comment by arnasbr** [comment]
I have a PR ready to merge for distance-map, I'll make sure it has this param too

**Review by arnasbr — APPROVED** [review]

**Comment by danielnaumau** [comment]
Heh, I think @pawel-wroniszewski didn't expect that he would get all approvals at 12.00 am

**Review by arnasbr — APPROVED** [review]
LGTM, thanks for the distance-map readme :)

**Pull request merged**
